// first_user_message derivation (#? session-title caveat bug).
//
// The sessions row's first_user_message is the display-title fallback and is
// COALESCE'd — first value wins permanently — so ingest must never seed it
// from synthetic user messages (local-command caveat, slash-command wrappers,
// isMeta events), and rows poisoned before those filters existed are repaired
// once by a migration that recomputes from the stored events.

import { afterEach, describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDb, closeDb, ingestLine } from './db.js';

const BARE_CAVEAT =
  'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.';

function freshDb(): string {
  const dir = mkdtempSync(join(tmpdir(), 'cf-db-fum-'));
  openDb(dir);
  return dir;
}

function fum(dir: string, sessionId: string): string | null {
  const row = openDb(dir)
    .prepare('SELECT first_user_message AS f FROM sessions WHERE id = ?')
    .get(sessionId) as { f: string | null } | undefined;
  return row?.f ?? null;
}

function userLine(
  uuid: string,
  content: string,
  extra: Record<string, unknown> = {},
): string {
  return JSON.stringify({
    type: 'user',
    uuid,
    timestamp: '2026-01-01T00:00:00.000Z',
    message: { role: 'user', content },
    ...extra,
  });
}

afterEach(() => closeDb());

describe('ingestLine first_user_message derivation', () => {
  it('skips the bare local-command caveat (older claude CLIs omit the wrapper tag)', () => {
    const dir = freshDb();
    try {
      ingestLine('ws-a', 's1', userLine('u1', BARE_CAVEAT, { isMeta: true }));
      ingestLine('ws-a', 's1', userLine('u2', '<bash-input>ls</bash-input>'));
      ingestLine('ws-a', 's1', userLine('u3', 'fix the login bug'));
      expect(fum(dir, 's1')).toBe('fix the login bug');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('skips isMeta user events even when their text matches no known wrapper', () => {
    const dir = freshDb();
    try {
      ingestLine('ws-a', 's2', userLine('u1', '[Image: original 2080x184]', { isMeta: true }));
      expect(fum(dir, 's2')).toBeNull();
      ingestLine('ws-a', 's2', userLine('u2', 'what does this screenshot show?'));
      expect(fum(dir, 's2')).toBe('what does this screenshot show?');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('migration 12: repair poisoned first_user_message', () => {
  // Simulates a DB written before the synthetic-prompt filters: events are
  // already ingested (so re-ingest dedupes and cannot heal the row), and the
  // sessions row holds a synthetic blob as its permanent title.
  function poison(dir: string, sessionId: string, value: string): void {
    const d = openDb(dir);
    d.prepare('UPDATE sessions SET first_user_message = ? WHERE id = ?').run(value, sessionId);
    d.pragma('user_version = 11');
    closeDb();
  }

  it('recomputes the title from the first real user prompt in events', () => {
    const dir = freshDb();
    try {
      ingestLine('ws-a', 's3', userLine('u1', BARE_CAVEAT, { isMeta: true }));
      ingestLine('ws-a', 's3', userLine('u2', '<bash-input>npm test</bash-input>'));
      ingestLine('ws-a', 's3', userLine('u3', 'why is CI red?'));
      poison(dir, 's3', BARE_CAVEAT);
      expect(fum(dir, 's3')).toBe('why is CI red?'); // reopen runs migration 12
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('clears the title to NULL when the session has no real prompt', () => {
    const dir = freshDb();
    try {
      ingestLine('ws-a', 's4', userLine('u1', BARE_CAVEAT, { isMeta: true }));
      ingestLine('ws-a', 's4', userLine('u2', '<bash-input>ls</bash-input>'));
      poison(dir, 's4', BARE_CAVEAT);
      expect(fum(dir, 's4')).toBeNull();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('leaves healthy titles untouched', () => {
    const dir = freshDb();
    try {
      ingestLine('ws-a', 's5', userLine('u1', 'ship the release'));
      const d = openDb(dir);
      d.pragma('user_version = 11');
      closeDb();
      expect(fum(dir, 's5')).toBe('ship the release');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
