// Parity test: the COMMITTED docker/qwen/qwenAdapter.mjs (generated by
// `npm run build:qwen-sidecar`) must produce IDENTICAL output to the TS source
// for all representative fixtures. If someone edits qwenAdapter.ts without
// regenerating the .mjs, this test fails loudly.
//
// Uses the same fixtures as src/main/qwenAdapter.test.ts.

import { describe, it, expect } from 'vitest';
// @ts-expect-error — .mjs import from TS; no type declarations, intentional
import { mapQwenRecord } from '../../docker/qwen/qwenAdapter.mjs';

const parse = (line: string | null) => (line ? JSON.parse(line) : null);

describe('qwenAdapter.mjs parity (generated bundle vs TS source)', () => {
  it('maps an assistant record with usage + model', () => {
    const out = parse(mapQwenRecord({
      type: 'assistant', uuid: 'u1', parentUuid: 'p0', timestamp: '2026-08-24T00:00:00.000Z',
      model: 'qwen3-coder:30b',
      usageMetadata: { promptTokenCount: 100, candidatesTokenCount: 20, cachedContentTokenCount: 5 },
      message: { role: 'model', parts: [{ text: 'hello' }] }
    }));
    expect(out.type).toBe('assistant');
    expect(out.uuid).toBe('u1');
    expect(out.message.model).toBe('qwen3-coder:30b');
    expect(out.message.usage.input_tokens).toBe(100);
    expect(out.message.usage.output_tokens).toBe(20);
    expect(out.message.usage.cache_read_input_tokens).toBe(5);
    expect(out.message.usage.service_tier).toBe('standard');
  });

  it('maps a tool call (functionCall → tool_use)', () => {
    const out = parse(mapQwenRecord({
      type: 'assistant', uuid: 'u2', timestamp: '2026-08-24T00:00:01.000Z', model: 'qwen3-coder:30b',
      message: { role: 'model', parts: [{ functionCall: { name: 'read_file', args: { path: 'a.ts' } } }] }
    }));
    const tu = out.message.content.find((b: { type: string }) => b.type === 'tool_use');
    expect(tu).toMatchObject({ type: 'tool_use', name: 'read_file', input: { path: 'a.ts' } });
    expect(typeof tu.id).toBe('string');
  });

  it('maps a tool result (functionResponse → tool_result)', () => {
    const out = parse(mapQwenRecord({
      type: 'tool_result', uuid: 'u3', timestamp: '2026-08-24T00:00:02.000Z',
      toolCallResult: { callId: 'call_1', status: 'success' },
      message: { role: 'user', parts: [{ functionResponse: { name: 'read_file', response: { content: 'x' } } }] }
    }));
    const tr = out.message.content.find((b: { type: string }) => b.type === 'tool_result');
    expect(tr).toMatchObject({ type: 'tool_result', tool_use_id: 'call_1', is_error: false });
  });

  it('maps a plain user record so message.content is a bare string', () => {
    const out = parse(mapQwenRecord({
      type: 'user', uuid: 'u4', timestamp: '2026-08-24T00:00:03.000Z',
      message: { role: 'user', parts: [{ text: 'do the thing' }] }
    }));
    expect(out.type).toBe('user');
    expect(typeof out.message.content).toBe('string');
    expect(out.message.content).toBe('do the thing');
  });

  it('uses functionCall.id fast-path when present', () => {
    const out = parse(mapQwenRecord({
      type: 'assistant', uuid: 'u5', timestamp: '2026-08-24T00:00:04.000Z', model: 'qwen3-coder:30b',
      message: { role: 'model', parts: [{ functionCall: { id: 'fc_id_123', name: 'read_file', args: { path: 'b.ts' } } }] }
    }));
    const tu = out.message.content.find((b: { type: string }) => b.type === 'tool_use');
    expect(tu.id).toBe('fc_id_123');
    expect(tu.name).toBe('read_file');
  });

  it('returns null for an unmappable (system) record', () => {
    expect(mapQwenRecord({ type: 'system', subtype: 'session_model' })).toBeNull();
  });
});
